/*

PLANETAS
IDPLANETA INT NOT NULL,
NOME VARCHAR(50) NOT NULL,
ROTACAO FLOAT NOT NULL,
ORBITA FLOAT NOT NULL,
DIAMETRO FLOAT NOT NULL,
CLIMA VARCHAR(50) NOT NULL,
POPULACAO INT NOT NULL

PILOTOS

PILOTOS_NAVES
IDPILOTO
IDNAVE

NAVES


*/

CREATE DATABASE EstrelaDaMorte;

USE EstrelaDaMorte
GO

CREATE TABLE PLANETAS(
IDPLANETA INT NOT NULL,
NOME VARCHAR(50) NOT NULL,
ROTACAO FLOAT NOT NULL,
ORBITA FLOAT NOT NULL,
DIAMETRO FLOAT NOT NULL,
CLIMA VARCHAR(50) NOT NULL,
POPULACAO INT NOT NULL
)
GO

ALTER TABLE PLANETAS ADD CONSTRAINT PK_PLANETAS PRIMARY KEY(IDPLANETA);

CREATE TABLE NAVES(
IDNAVE INT PRIMARY KEY,
NOME VARCHAR(100),
MODELO VARCHAR(100),
PASSAGEIROS INT,
CARGA FLOAT,
CLASSE VARCHAR(100)
);

CREATE TABLE PILOTOS(
IDPILOTO INT NOT NULL,
NOME VARCHAR(200) NOT NULL,
ANONASCIMENTO VARCHAR(10) NOT NULL,
IDPLANETA INT NOT NULL
)
GO
ALTER TABLE PILOTOS ADD CONSTRAINT PK_PILOTOS PRIMARY KEY (IDPILOTO)
GO
ALTER TABLE PILOTOS ADD CONSTRAINT FK_PILOTOS_PLANETAS FOREIGN KEY (IDPLANETA)
REFERENCES PLANETAS(IDPLANETA);

CREATE TABLE PILOTOSNAVES(
	IDPILOTO INT NOT NULL,
	IDNAVE INT NOT NULL,
	FLAGAUTORIZADO BIT NOT NULL
)
GO

ALTER TABLE PILOTOSNAVES ADD CONSTRAINT PK_PILOTOSNAVES PRIMARY KEY (IDPILOTO, IDNAVE)
GO
ALTER TABLE PILOTOSNAVES ADD CONSTRAINT FK_PILOTOSNAVES_PILOTOS FOREIGN KEY (IDPILOTO)
REFERENCES PILOTOS(IDPILOTO)
GO
ALTER TABLE PILOTOSNAVES ADD CONSTRAINT FK_PILOTOSNAVES_NAVES FOREIGN KEY (IDNAVE)
REFERENCES NAVES(IDNAVE)
GO
ALTER TABLE PILOTOSNAVES ADD CONSTRAINT DF_PILOTOSNAVES_FLAGAUTORIZADO DEFAULT(1) FOR FLAGAUTORIZADO;

-- HISTÓRICO DE VIAGENS

CREATE TABLE HISTORICOVIAGENS(
	IDNAVE INT NOT NULL,
	IDPILOTO INT NOT NULL,
	DTSAIDA DATETIME NOT NULL,
	DTCHEGADA DATETIME NULL
);

ALTER TABLE HISTORICOVIAGENS ADD CONSTRAINT FK_HISTORICOVIAGENS_PILOTOSNAVES FOREIGN KEY (IDPILOTO, IDNAVE)
REFERENCES PILOTOSNAVES(IDPILOTO, IDNAVE)
GO
ALTER TABLE HISTORICOVIAGENS CHECK CONSTRAINT FK_HISTORICOVIAGENS_PILOTOSNAVES;