CREATE DATABASE YT;

USE YT;

CREATE TABLE VIDEOS(
	IDVIDEO int PRIMARY KEY AUTO_INCREMENT,
	AUTHOR TEXT,
	TITLE VARCHAR(40),
	LIKES INT,
	DISLIKES INT
);

INSERT INTO VIDEOS(AUTHOR, TITLE, LIKES, DISLIKES) VALUES('MARIA','MYSQL', 10,2);
INSERT INTO VIDEOS(AUTHOR, TITLE, LIKES, DISLIKES) VALUES('JOAO', 'HTML', 30, 1);
INSERT INTO VIDEOS(AUTHOR, TITLE, LIKES, DISLIKES) VALUES('MARIA', 'css', 18, 3);
INSERT INTO VIDEOS(AUTHOR, TITLE, LIKES, DISLIKES) VALUES('PEDRO', 'JAVASCRIPT', 15, 0);
INSERT INTO VIDEOS(AUTHOR, TITLE, LIKES, DISLIKES) VALUES('MARIA', 'PYTHON', 50, 0);
INSERT INTO VIDEOS(AUTHOR, TITLE, LIKES, DISLIKES) VALUES(2, 'PHP', 20, 8);
SELECT * FROM VIDEOS;
SELECT AUTHOR FROM VIDEOS;

ALTER TABLE VIDEOS MODIFY AUTHOR INT;

ALTER TABLE VIDEOS ADD CONSTRAINT FK_AUTHOR
FOREIGN KEY (AUTHOR) REFERENCES AUTHOR(IDAUTHOR);

ALTER TABLE VIDEOS ADD COLUMN FK_SEO INT NOT NULL AFTER TITLE;

ALTER TABLE VIDEOS ADD CONSTRAINT FK_SEO
FOREIGN KEY (FK_SEO) REFERENCES SEO(IDSEO);

DESC VIDEOS;

CREATE TABLE AUTHOR(
	IDAUTHOR INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(30),
	BORN DATE
);

INSERT INTO AUTHOR(NAME, BORN) VALUES('MARIA', '1992-04-19');
INSERT INTO AUTHOR(NAME, BORN) VALUES('PEDRO', '1987-03-25');
INSERT INTO AUTHOR(NAME, BORN) VALUES('JOAO', '1998-03-09');
INSERT INTO AUTHOR(NAME, BORN) VALUES('FLAVIA', '2000-12-05');
SELECT * FROM AUTHOR;

SELECT VIDEOS.IDVIDEO, AUTHOR.NAME, VIDEOS.TITLE, VIDEOS.FK_SEO, LIKES, DISLIKES FROM VIDEOS 
INNER JOIN AUTHOR ON VIDEOS.AUTHOR = AUTHOR.IDAUTHOR;

CREATE TABLE SEO(
	IDSEO INT PRIMARY KEY AUTO_INCREMENT,
	CATEGORY VARCHAR(30)
);

INSERT INTO SEO (CATEGORY) VALUES('FRONTEND');
INSERT INTO SEO (CATEGORY) VALUES('BACKEND');

SELECT * FROM VIDEOS;
SELECT * FROM SEO;

UPDATE VIDEOS SET FK_SEO=1 WHERE IDVIDEO = 2;
UPDATE VIDEOS SET FK_SEO=1 WHERE IDVIDEO = 3;
UPDATE VIDEOS SET FK_SEO=1 WHERE IDVIDEO = 4;

UPDATE VIDEOS SET FK_SEO=2 WHERE IDVIDEO = 5;
UPDATE VIDEOS SET FK_SEO=2 WHERE IDVIDEO = 6;

DESC VIDEOS;
SELECT VIDEOS.TITLE, AUTHOR.NAME, SEO.CATEGORY FROM VIDEOS JOIN SEO ON VIDEOS.FK_SEO = SEO.IDSEO
JOIN AUTHOR ON VIDEOS.AUTHOR = AUTHOR.IDAUTHOR;


CREATE TABLE PLAYLIST(
IDPLAYLIST INT PRIMARY KEY AUTO_INCREMENT,
NAMEPL VARCHAR(30)
);

ALTER TABLE PLAYLIST ADD FK_AUTHOR INT NOT NULL AFTER NAMEPL;

ALTER TABLE PLAYLIST ADD CONSTRAINT PLAYLIST_AUTHOR FOREIGN KEY (FK_AUTHOR) REFERENCES AUTHOR(IDAUTHOR);

DESC PLAYLIST;

INSERT INTO PLAYLIST(NAMEPL) VALUES('HTML + CSS');
INSERT INTO PLAYLIST(NAMEPL) VALUES('HTML + PHP + JS');
INSERT INTO PLAYLIST(NAMEPL) VALUES('PYTHON + PHP');
SELECT * FROM PLAYLIST;
SELECT * FROM VIDEOS;

CREATE TABLE VIDEOS_PLAYLIST(
ID_VP INT PRIMARY KEY AUTO_INCREMENT,
FK_VIDEOS INT,
FK_PLAYLIST INT
);

INSERT INTO VIDEOS_PLAYLIST(FK_VIDEOS, FK_PLAYLIST) VALUES(2,1);
INSERT INTO VIDEOS_PLAYLIST(FK_VIDEOS, FK_PLAYLIST) VALUES(3,1);

SELECT PLAYLIST.NAMEPL, VIDEOS.TITLE, AUTHOR.NAME FROM PLAYLIST 
JOIN VIDEOS_PLAYLIST ON PLAYLIST.IDPLAYLIST = VIDEOS_PLAYLIST.FK_PLAYLIST
JOIN VIDEOS ON VIDEOS.IDVIDEO = VIDEOS_PLAYLIST.FK_VIDEOS
JOIN AUTHOR ON AUTHOR.IDAUTHOR = VIDEOS.AUTHOR;


INSERT INTO VIDEOS_PLAYLIST(FK_VIDEOS, FK_PLAYLIST) VALUES(,);
INSERT INTO VIDEOS_PLAYLIST(FK_VIDEOS, FK_PLAYLIST) VALUES(,);